//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBookCommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.Baskets = new HashSet<Basket>();
        }
    
        public int paymentId { get; set; }
        public string paymentOrderId { get; set; }
        public string paymentOrderNumber { get; set; }
        public Nullable<decimal> paymentAmount { get; set; }
        public string paymentUserName { get; set; }
        public string paymentEmail { get; set; }
        public Nullable<int> paymentStatus { get; set; }
        public Nullable<decimal> paymentApprovedAmount { get; set; }
        public string paymentMaskedPan { get; set; }
        public string paymentCardholderName { get; set; }
        public string paymentErrorCode { get; set; }
        public string paymentErrorMessage { get; set; }
        public Nullable<System.DateTime> paymentCreatedAt { get; set; }
        public Nullable<System.DateTime> paymentUpdatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basket> Baskets { get; set; }
    }
}
